### ISSUE TITLE
Abertura do Documento de Visão

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#10]
## Descrição da Issue
Realizar a abertura sobre documento de visão.

## Tasks:
- [x] Estudar sobre DV (#6 e treinamento sobre documentos)
- [x] Criação do DV

## Critérios de Aceitação:
- [x] Abertura do documento de visão

**Comment by CarlosFiuza** [comment]
Finalizado com sucesso a abertura do documento de visão. Disponível para alteração pela equipe. 
link: https://docs.google.com/document/d/1QjYB4kTWhqxCLv0SIs-AcUk7WZH-ZMlBcVdGbImzo_Q/edit?usp=sharing
Autores: Brenno Oliveira e Carlos Eduardo.
