### ISSUE TITLE
[US14] - Pesquisar Localização

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#100]
## Descrição da Issue
- Eu, como comprador, gostaria de pesquisar um anúncio pela localização

## Tasks:
- [x] Adaptar interface no frontend
- [x] Criar rota de pesquisa no backend

## Critérios de Aceitação:
- [x] Ser possível pesquisar anúncios pela localização
- [x] Testes no frontend
- [x] Testes no backend
