### ISSUE TITLE
[US17] - Adicionar Produtor a Lista de Favoritos

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#103]
## Descrição da Issue
- Eu, como comprador, gostaria de adicionar um produtor a lista de favoritos

## Tasks:
- [x] Criar tela "Produtores Favoritos"
- [x] Dar funcionalidade ao botão de "favoritar"
- [x] Criar rotas no backend

## Critérios de Aceitação:
- [x] Ser possível favoritar produtor
- [x] Realizado testes no backend
- [x] Realizado testes no frontend
