### ISSUE TITLE
[US21] - Denunciar Usuário

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#107]
## Descrição da Issue
- Eu, como usuário, gostaria de denunciar outro usuário

## Tasks:
- [x] Adaptar interface no frontend
- [x] Adição de telas no protótipo
- [x] Adição de atributo ao produtor
- [x] Rota para listar reclamações
- [x] Classes para criar reclamação

## Critérios de Aceitação:
- [x] Manter % de coverage dos testes
- [x] Testes no backend
- [x] Testes no frontend
- [x] Interface utilizável no frontend
- [x] Backend seguindo padrão do projeto
