### ISSUE TITLE
Abertura do Documento de Arquitetura

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#11]
## Descrição da Issue
Realizar a abertura sobre documento de arquitetura.

## Tasks:
- [x] Estudar sobre DA (#6  e treinamento sobre documentos)
- [x] Criação do DA

## Critérios de Aceitação:
- [x] Abertura do documento de arquitetura

## Assignees
A definição de assignees deve ser feita por quem se sentir a vontade. Definir ao menos até segunda feira (15/02)
