### ISSUE TITLE
Conexão tela de login e tela de registro

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#113]
## Descrição da Issue
Fazer a conexão entre a tela de login e a tela de registro.

## Tasks:
- [x] Refatorar User do Backend para diferenciar os dois tipos de usuários
- [x] Atualizar Frontend para cadastrar devidos usuários

## Critérios de Aceitação:
- [x] Ter diferenciado os dois tipos de usuário 
- [x] Interface estar funcionando
