### ISSUE TITLE
Tela principal do Comprador e do Produtor

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#114]
## Descrição da Issue
Implementação das telas principais do produtor e outra do comprador.

## Tasks:
- [x] Criar tela para o Comprador
- [x] Criar tela para o Produtor
- [x] Identificar se um User é um produtor ou comprador
- [x] Redirecionamento correto nas routers

## Critérios de Aceitação:
- [x] Estar funcionando
- [x] Telas seguirem o protótipo
