### ISSUE TITLE
Melhoria do protótipo de alta fidelidade

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#115]
## Descrição da Issue
Atualização do protótipo de alta fidelidade para adição e refatoração de novas telas.

## Tasks:
- [x] Adicionar novas telas
- [x] Atualizar nomes das telas no Figma
- [x] Atualizar página na wiki

## Critérios de Aceitação:
- [x] Ter adicionado novas telas
- [x] Atualizado wiki
