### ISSUE TITLE
Revisão dos documentos de arquitetura

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#116]
## Descrição da Issue
Revisar documento de arquitetura para adicionar as devidas mudanças

## Tasks:
- [x] Atualizar MER e DER
- [x] Atualizar Diagrama de Casos de Uso
- [x] Adicionar Diagrama de Pacotes
- [x] Adicionar a Visão Lógica

## Critérios de Aceitação:
- [x] Estar na wiki
