### ISSUE TITLE
Documentos de Metodologia e Tecnologia

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#12]
## Descrição da Issue
Estudo e formulação dos documentos de metodologia e tecnologia.

## Tasks:
- [x] Estudar sobre documento de metodologia
- [x] Estudar sobre documento de tecnologia
- [x] Pesquisar nos repositórios

## Critérios de Aceitação:
- [x] Geração do documento de metodologia
- [x] Geração do documento de tecnologia
