### ISSUE TITLE
Preparação e apresentação para a Release 1

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#128]
## Descrição da Issue
Reunir todo o grupo para preparar e gravar apresentação da Release 1.

## Tasks:
- [x] Definir tópicos a serem abordados
- [x] Definir plataforma para gravar
- [x] Criar slides
- [x] Gravar apresentação
- [x] Definir e adicionar os processos de releases no github

## Critérios de Aceitação:
- [x] Finalizar tasks antes das 20:00 horas de Segunda-feira
