### ISSUE TITLE
Linkar o backend do list de anúncios com o frontend 

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#141]
## Descrição da Issue
Fazer a ligação entre o backend da lista de produtos com a página inicial do comprador no frontend.

## Tasks:
- [x] List de produtos no backend
- [x] Puxar informações do backend ao frontend

## Critérios de Aceitação:
- [x] Seguir protótipo
- [x] Estar retornando informações corretas
