### ISSUE TITLE
Gerar documentação sobre planning sprint 8

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#145]
## Descrição da Issue
- O Scrum Master deve gerar a documentação sobre a Sprint 8.

## Tasks:
- [x] Documentar sobre o planning
- [x] Abertura de Release

## Critérios de Aceitação:
- [x] Estar na Wiki
- [x] Estar padronizada
