### ISSUE TITLE
Linkar Backend com a homepage do Produtor

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#157]
## Descrição da Issue
Fazer a ligação entre o backend da lista de produtos com a página inicial do produtor no frontend.

## Tasks:
- [x] List de produtos no backend
- [x] Puxar informações do backend ao frontend
- [x] Fazer viewset e rotas para requisição dos anúncios

## Critérios de Aceitação:
- [x] Seguir protótipo
- [x] Estar retornando informações corretas
- [x] Fazer testes
