### ISSUE TITLE
Refatorar viewsets de anúncio

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#158]
## Descrição da Issue
Refatorar viewset dos anúncios para melhorar utilização

## Tasks:
- [x] Padronizar viewset
- [x] Refatorar e condensar viewsets
- [x] Remover a utilização do "email" no corpo da rota de criar anúncio
- [x] Refatorar o front para as novas viewsets

## Critérios de Aceitação:
- [x] Utilização de testes
- [x] O código ter se tornado o mais enchuto possível
