### ISSUE TITLE
Criação da tela Detalhes Anúncio

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#161]
## Descrição da Issue
Criação da página de anúncio de acordo com o protótipo.

## Tasks:
- [x] Desenvolver tela "Detalhes Anúncio"

## Critérios de Aceitação:
- [x] Tela seguir o protótipo
- [x] Utilização de testes
