### ISSUE TITLE
Codequality, lint (CI e CD), coverage

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#162]
## Descrição da Issue
Implementação de ferramentas de code quality.

## Tasks:
-  [x]  Implementar Codequality no Backend
-  [x]  Implementar Codequality no Frontend
-  [x]  Atualizar workflow CI com verificação de Codequality 
- [x] Atualizar workflow CD, se necessário.
- [x] Implementar Code coverage no Backend
- [x] Implementar Code coverage no Frontend

## Critérios de Aceitação:
- [x]  Realizar verificação de Codequality a cada pull request
- [x] Bagde de Coverage no README
- [x]  Workflows funcionando perfeitamente

**Comment by CarlosFiuza** [comment]
Implementação de revisão Codequality realizada no workflow CI

**Comment by CarlosFiuza** [comment]
Revisão Codequality realizada e erros apontados corrigidos

**Comment by CarlosFiuza** [comment]
Adicionado ao backend code coverage no workflow CI e Badge para codecov no readme.

**Comment by matheuscvp** [comment]
Code coverage, adicionado ao repositório do frontend, ele poderá ser observado a partir de uma badge no README do mesmo.

**Comment by matheuscvp** [comment]
Codequality usado no front foi o Flint, para mais informações acessar o [pr](https://github.com/fga-eps-mds/2020.2-Hortum-Mobile/pull/29), onde está melhor descrito.
