### ISSUE TITLE
Interações com email

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#163]
## Descrição da Issue
Implementação de verificação de email.

## Tasks:
- [x] Implementar sistema de envio de email
- [x] Enviar email para confirmar cadastro

## Critérios de Aceitação:
- [x] Utilização de testes
- [x] Envio de emails ao usuário
