### ISSUE TITLE
Implementação dos testes que faltam

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#164]
## Descrição da Issue
Criação de testes para métodos sem testes.

## Tasks:
- [x] Teste para excluir anúncio inexistente
- [x] Teste para editar nome do anúncio para um já existente
- [x] Teste para cadastro de usuário com email já existente
- [x] Teste para cadastro com algum atributo vazio
- [x] Teste de token válido para usuário

## Critérios de Aceitação:
- [x] Implementação dos testes escritos na "Tasks"
