### ISSUE TITLE
Gerar documentação sobre planning sprint 9

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#166]
## Descrição da Issue
- O Scrum Master deve gerar a documentação sobre a Sprint 9.

## Tasks:
- [x] Documentar sobre o planning
- [ ] Abertura de Release

## Critérios de Aceitação:
- [x] Estar na Wiki
- [x] Estar padronizada
