### ISSUE TITLE
Definição e Documentação do Backlog do Produto (User Stories)

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#17]
## Descrição da Issue
O Product Owner deverá pensar e analisar os épicos e features (#8) para gerar as user stories das próximas sprints.

## Tasks:
- [x] Estudar épicos e features
- [x] Pensar nas user stories
- [x] Documentar

## Critérios de Aceitação:
- [x] Estar de acordo com épicos e features
- [x] Estar na wiki (github pages)
- [x] Ter ao menos 5 user stories (neste momento inicial)

## Assignees
Quando o product owner for definido, deve-se imediatamente adiciona-lo a esta issue
