### ISSUE TITLE
Alterar ordenação de anúncios na Homepage do comprador

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#181]
## Descrição da Issue
- Alterar a forma como os anúncios são ordenados de forma que os mais recentes sejam mostrados primeiro.

## Tasks:
- [x] Alterar a maneira que itens são retornados do banco de dados para mostrar os mais recentes primeiro.

## Critérios de Aceitação:
- [x] Anúncios sendo retornados em ordem de publicação.
- [x] Realização de testes unitários
