### ISSUE TITLE
Adição do Swaggers

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#192]
## Descrição da Issue
- Adição da página de Swaggers

## Tasks:
- [x] Implementar swaggers ao backend

## Critérios de Aceitação:
- [x] Swaggers funcional localmente
- [x] Swaggers funcional em ambiente de produção

**Comment by matheuscvp** [comment]
O Acesso ao swagger, documentação da API, está disponível através de um link que está no README.
