### ISSUE TITLE
Adição de testes ao frontend

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#193]
## Descrição da Issue
- Implementação de testes inexistentes ao frontend.

## Tasks:
- [x] Adicionar testes aos frontend

## Critérios de Aceitação:
- [x] Aumentar para 90% de coverage dos testes
- [x] Testes no frontend

**Comment by matheuscvp** [comment]
Feito com sucesso! Parabéns aos envolvidos!
