### ISSUE TITLE
Adição de número de telefone do produtor

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#194]
## Descrição da Issue
- Adição do número de telefone ao produtor

## Tasks:
- [x] Adaptar interface de Cadastro,
- [x] Adaptar interface da Tela de perfil
- [x] Adaptar interface de Atualizar dados
- [x] Adição de atributo ao produtor
- [x] Refatoração de classes de editar usuário 
- [x] Refatoração de classes de registrar produtor

## Critérios de Aceitação:
- [ ] Manter % de coverage dos testes
- [x] Testes no backend
- [x] Testes no frontend
- [x] Interface utilizável no frontend
- [x] Backend seguindo padrão do projeto
