### ISSUE TITLE
Pesquisa/Base sobre Front-end (Flutter)

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#20]
## Descrição da Issue
Pesquisar e desenvolver a base para a programação front-end com o flutter.

## Tasks:
- [x] Pesquisar sobre o flutter
- [x] Desenvolver uma base para a programação
- [x] Gerar documentação para a equipe

## Critérios de Aceitação:
- [x] Documento disponível para o grupo
- [ ] Base deve estar em seu repositório correto (#27)

**Comment by CarlosFiuza** [comment]
Pesquisa e documentação feita, documento disponível no drive do grupo.
[Documentação Flutter](https://docs.google.com/document/d/1fuYJOsERcyLAkCR8Judu-nriAzMT2j6LkQij5MTy-TU/edit?usp=sharing)
