### ISSUE TITLE
Correções na tela detalhes do produtor

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#204]
## Descrição da Issue
- Correção do overflow no nome do produtor e corrigir erro caso o produtor não tenha nenhum anúncio.

## Tasks:
- [x] Correção do overflow no nome
- [x] Correção ao não haver anúncio

## Critérios de Aceitação:
- [ ] Manter % dos testes
- [x] Seguir protótipo
