### ISSUE TITLE
Melhorias gerais na apresentação do aplicativo

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#206]
## Descrição da Issue
- Alterar logo, nome do aplicativo, remover README(da pasta /hortum_mobile/) do frontend, e tag de debug.

## Tasks:
- [x] Alterar ícone ao instalar o aplicativo
- [x] Alterar nome do aplicativo ao instalar
- [x] Remover README
- [x] Remover tag de debug

## Critérios de Aceitação:
- [x] Todas as tasks serem feitas
