### ISSUE TITLE
Atualizar Documentação

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#207]
## Descrição da Issue
- Atualizar o Documento de Visão, Arquitetura e Product Backlog.

## Tasks:
- [x] Correção dos modelos do banco
- [x] Correção do diagrama entidade relacionamentos
- [x] Correção dos casos de uso
- [x] Remoção de features do Documento de Visão
- [x] Remoção de US do Product Backlog

## Critérios de Aceitação:
- [x] Realizado tasks
