### ISSUE TITLE
Correção de categorias

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#208]
## Descrição da Issue
- Arrumar categorias da homepage do Customer e diminuir categorias do backend

## Tasks:
- [x] Alterar categorias do backend
- [x] Criar rota para recebimento de anuncios de tal categoria/tipo
- [x] Refatorar carrossel
- [x] Alterar categorias do frontend

## Critérios de Aceitação:
- [x] Refatorar categorias
- [x] Rota estar funcionando corretamente
- [x] Manter a porcentagem de cobertura de testes

**Comment by matheuscvp** [comment]
Adicionado rota para requisição de anúncios com base na categoria escolhida.
