### ISSUE TITLE
Integrar imagens ao frontend

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#209]
## Descrição da Issue
- Implementar a possibilidade de enviar imagens pelo aplicativo

## Tasks:
- [x] Remover imagens estáticas de usuário e de anúncios
- [x] Possibilitar selecionar imagens
- [x] Permitir enviar imagens

## Critérios de Aceitação:
- [x] Manter % dos testes
- [x] Integração das imagens
