### ISSUE TITLE
Pesquisa/Base sobre Back-end (Django)

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#21]
## Descrição da Issue
Pesquisar e desenvolver a base para a programação back-end com o django.

## Tasks:
- [x] Pesquisar sobre o django
- [x] Desenvolver uma base para a programação
- [x] Gerar documentação para a equipe

## Critérios de Aceitação:
- [x] Documento disponível para o grupo
- [x] Base deve estar em seu repositório correto (#27)

**Comment by Joao-Moura** [comment]
[Docs sobre as pastas do Django](https://docs.google.com/document/d/14IdIGToviwQDQ1qKPZlHOqhASAcTbLd-vf_b9ihskoI/edit?usp=sharing).
