### ISSUE TITLE
Implementação do Dio no lugar do http

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#214]
## Descrição da Issue
- Refatoração dos Datas que ainda utilizam http para colocar o Dio no lugar.

## Issues relacionadas
- [#27](https://github.com/fga-eps-mds/2020.2-Hortum-Mobile/issues/27)

## Tasks:
- [x] Alteração no auto_login

## Critérios de Aceitação:
- [x] Alteração no auto login
- [x] Correção em testes(Caso necessário)
