### ISSUE TITLE
Pesquisa/Base sobre Docker

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#22]
## Descrição da Issue
Pesquisar e desenvolver a base para o uso de dockers.

## Tasks:
- [x] Pesquisar sobre o docker
- [x] Desenvolver uma base para o uso
- [x] Gerar documentação para a equipe

## Critérios de Aceitação:
- [x] Documento disponível para o grupo
- [x] Base de docker usável

**Comment by brenno-silva** [comment]
Link do [Documento do Docker](https://docs.google.com/document/d/1Xh7N1RrAJtmF262qBlsL85ueQAxEo037vrW0WwbqoEg/edit)
