### ISSUE TITLE
Refatoração no Backend

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#221]
## Descrição da Issue
- Alterar viewsets e serializers visando melhor apresentabilidade do código.

## Tasks:
- [x] Refatoração serializers
- [x] Melhorias e padronizações das viewsets
- [x] Análise das rotas
- [x] Melhoria dos testes
- [x] Adição de novas permissões
- [x] Adição de validators
- [x] Melhoria da funcionalidade de favoritar anúncios

## Critérios de Aceitação:
- [x] Código estar mais consiso
- [x] Aumento do coverage
- [x] Redução dos bad smells do code quality
