### ISSUE TITLE
Protótipo de Baixa Fidelidade

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#23]
## Descrição da Issue
Gerar um protótipo de baixa fidelidade para a equipe.

## Tasks:
- [x] Pensar sobre o protótipo
- [x] Gerar suas fotos/desenhos

## Critérios de Aceitação:
- [x] O grupo deve estar satisfeito (todos fazem review)
- [x] As imagens devem estar documentadas na wiki
