### ISSUE TITLE
Incrementação do Documento de arquitetura

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#24]
## Descrição da Issue
Deve-se incrementar/melhorar/adicionar o documento de arquitetura ja existente.

## Tasks:
- [x] Melhorar o documento
- [x] Adicionar novos tópicos

## Critérios de Aceitação:
- [x] Deve conter ao menos os casos de uso
- [x] Deve estar de acordo com a formatação

**Comment by matheuscvp** [comment]
https://lucid.app/lucidchart/invitations/accept/d7dad3af-62f7-4d04-bfb7-76553ea630cd

Link do diagrama de casos de uso
