### ISSUE TITLE
Gerar documentação sobre review sprint 1

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#25]
## Descrição da Issue
O scrum master deve gerar a documentação sobre a sprint 1

## Tasks:
- [x] Documentar sobre a review
- [x] Documentar sobre a retrospective

## Critérios de Aceitação:
- [x] Estar na wiki
- [x] Estar padronizada
