### ISSUE TITLE
Modularização do repositório

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#27]
## Descrição da Issue
O repositório deve passar por uma modularização.

## Tasks:
- [x] Separar os repositórios

## Critérios de Aceitação:
- [x] Repositório para o Front-End
- [x] Repoistório para o Back-End e para documentação
