### ISSUE TITLE
Incrementação da política de contribuição

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#31]
## Descrição da Issue
- Deve-se fazer a melhoria do documento de política de contribuição

## Tasks:
- [x] Adicionar política de Pull Requests
- [x] Adicionar política de Branchs
- [x] Adicionar política de Issues (Dúvidas, US, Issues, Bug)
- [x] Adicionar demais temas que achar necessário

## Critérios de Aceitação:
- [x] Descrição sobre os Pull Requests
- [x] Descrição sobre as Branchs
- [x] Descirção sobre as Issues
- [x] Adicionar à wiki
