### ISSUE TITLE
Incrementação do Documento de Visão

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#41]
## Descrição da Issue
- Evolução do Documento de Visão.

## Tasks:
- [x] Adicionar novos tópicos

## Critérios de Aceitação:
- [x] Adicionar pelo menos 1 novo tópico
- [x] Estar na wiki
