### ISSUE TITLE
Criação do Docker para o Backend

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#42]
## Descrição da Issue
- Adição do ambiente docker para o backend

## Tasks:
- [x] Estudo sobre o Docker (#22)
- [x] Implementação no repositório

## Critérios de Aceitação:
- [x] Docker para o backend
