### ISSUE TITLE
Canvas do Produto

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#43]
## Descrição da Issue
- Formulação do Canvas do produto

## Tasks:
- [x] Estudo sobre canvas
- [x] Análise do canvas sobre o produto

## Critérios de Aceitação:
- [x] Canva na wiki do projeto
