### ISSUE TITLE
Organização arquitetural do banco de dados

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#44]
## Descrição da Issue
- Estudo e representação arquitetural do banco de dados do projeto

## Tasks:
- [x] Estudar sobre banco de dados
- [x] Estudar como o Django/Postgresql funcionam
- [x] Documentação dessa representação

## Critérios de Aceitação:
- [x] Representação arquitetural no documento de arquitetura
- [ ] Documento de estudo para o grupo
