### ISSUE TITLE
Protótipo de alta fidelidade

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#45]
## Descrição da Issue
- Definição do protótipo de alta fidelidade

## Tasks:
- [x] Estudo sobre o projeto
- [x] Documentação sobre o protótipo

## Critérios de Aceitação:
- [x] Documento de protótipo de alta fidelidade
