### ISSUE TITLE
Implementação do Banco de Dados

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#58]
## Descrição da Issue
- Implementação do banco de dados (postgreSQL) e suas entidades.

## Tasks:
- [x] Estudo sobre como implementar
- [x] Utilizar o documento de arquitetura #44 

## Critérios de Aceitação:
- [x] Ter as entidades representadas do documento de arquitetura
- [x] Possuir seus serializers
- [ ] Testar se ao menos o banco está sendo criado (fotos)
