### ISSUE TITLE
[US01] - Cadastro de conta

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#61]
## Descrição da Issue
- Eu, como usuário, gostaria de me cadastrar na plataforma.

## Tasks:
- [x] Rotas do backend
- [x] Frontend simplório para testes

## Critérios de Aceitação:
- [x] O backend deve estar pronto e funcional
- [x] O frontend deve possuir o mínimo para teste
- [x] Possuir capturas de tela sobre a implementação e uso
