### ISSUE TITLE
Documentação dos Casos de Uso

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#65]
## Descrição da Issue
- Documentas os casos de uso e usuários do programa no documento de arquitetura

## Tasks:
- [x] Usuários do programa
- [x] Casos de uso

## Critérios de Aceitação:
- [x] Possuir diagrama de casos de uso
- [x] Ser baseada no backlog do produto
- [x] Estar padronizada
- [x] Estar na wiki
