### ISSUE TITLE
Definir identidade visual do projeto

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#66]
## Descrição da Issue
- Definição da identidade visual do projeto

## Tasks:
- [x] Dscussão com o grupo sobre a logo
- [x] Discussão sobre paleta de cores
- [x] Discussão sobre fonte
- [x] Discussão sobre botões, caixas de texto, etc

## Critérios de Aceitação:
- [x] Estar de acordo com o tema do projeto
- [x] Documentada na wiki
- [x] Grupos estar satisfeito
