### ISSUE TITLE
Treinamento backend e suas tecnologias

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#68]
## Descrição da Issue
- Fornecer um treinamento sobre o backend

## Tasks:
- [ ] Planejar apresentação
- [x] Cobrir pontos importantes sobre o backend

## Critérios de Aceitação:
- [x] Documento disponível para o grupo
- [ ] Apresentação disponível para assistir novamente
