### ISSUE TITLE
Treinamento frontend e suas tecnologias

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#69]
## Descrição da Issue
- Fornecer um treinamento sobre o frontend

## Tasks:
- [ ] Planejar apresentação
- [ ] Cobrir pontos importantes sobre o frontend

## Critérios de Aceitação:
- [ ] Documento disponível para o grupo
- [ ] Apresentação disponível para assistir novamente
