### ISSUE TITLE
Documentação de Sprints (sprint 0 inclusa)

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#7]
## Descrição da Issue
Documentar as sprints semanais e também a sprint 0.

## Tasks:
- [x] Definir um template para a documentação
- [x] Documentar a sprint 0

## Critérios de Aceitação:
- [x] Descrever o Planning para a Sprint 0
- [x] Descrever a Review para a Sprint 0
