### ISSUE TITLE
Estudo e implementação Heroku

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#70]
## Descrição da Issue
Implementação do Heroku para utilização do backend.

## Tasks:
- [x] Estudar sobre o Heroku
- [x] Implementar backend no Heroku
- [x] Documentar

## Critérios de Aceitação:
- [x] Estar funcionando
- [x] Ter documentado para o grupo
