### ISSUE TITLE
Melhoria dos README's do Frontend e do Backend

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#78]
## Descrição da Issue
- O README deve ser evoluido a um estágio próximo ao final para a Release 1

## Tasks:
- [x] Estudar README's de repositórios anteriores/externos
- [x] Melhorar README backend
- [x] Melhorar README frontend
- [x] Estudar sobre badges para usar no README

## Critérios de Aceitação:
- [x] Deve possuir um resumo sobre o projeto
- [ ] Possuir algumas screenshots (talvez não agora)
- [x] Deve possuir passos para instalação/uso
- [x] Os desenvolvedores/contribuidores do projeto
