### ISSUE TITLE
Revisão de documentos da wiki

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#79]
## Descrição da Issue
- Correção ortográfica dos documentos da wiki

## Tasks:
- [x] Revisar todos os documentos
- [x] Encontrar melhores frases/parágrafos
- [x] Corrigir erros de arquivos (se houver)

## Critérios de Aceitação:
- [x] Correção ortográfica
- [x] Correção de arquivos (se houver)
