### ISSUE TITLE
Definição de Épicos e Features (backlog do produto)

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#8]
## Descrição da Issue
O grupo deve focar suas atividades em gerar os épicos e features para o projeto. Compartilhar via dontpad ou docs, para posterior inserção em backlog de produto.

## Tasks:
- [x] Estudar sobre o tema do projeto;
- [x] Pensar globalmente sobre o projeto;
- [x] Pensar sobre possíveis adições;

## Critérios de Aceitação:
- [x] Gerar ao menos 2 épicos
- [x] Gerar pelo menos 4 feautures
- [x] Estar de acordo com o tema proposto para o projeto

**Comment by Joao-Moura** [comment]
[Docs para o grupo](https://docs.google.com/document/d/1l8LILhkAYpSYx0yoZoQ0LDgYn8ulNwMSxEIx2_KoYU4/edit)
