### ISSUE TITLE
Customização do mkdocs e organização dos documentos

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#80]
## Descrição da Issue
- Melhoria/customização da wiki do projeto de acordo com o estilo visual proposto e organização dos documentos em pastas específicas.

## Tasks:
- [x] Estudo sobre os estilos visuais (#66)
- [x] Estudo sobre possíveis adições de plugins ao mkdocs (se interessantes)
- [x] Customizar o mkdocs de acordo com as paletas e fontes
- [x] Pensar em formas de organizar os documentos (se basear em outros repos)

## Critérios de Aceitação:
- [x] Fontes de acordo com a proposta visual do projeto
- [x] Paleta de cores de acordo com a proposta visual do projeto
- [x] Documentos oganizados de forma lógica
