### ISSUE TITLE
[US03] - Login de Conta

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#81]
## Descrição da Issue
- Eu, como usuário, gostaria de logar na minha conta.

## Tasks:
- [x] Capacitação do frontend para requisições
- [x] Capacitar a API para login em contas
- [x] Autenticação para realização de requisições (Tokens)

## Critérios de Aceitação:
- [x] Frontend deve estar como foi definido na identidade visual do projeto
- [x] Backend ser capaz de receber as autenticações
- [x] Fotos mostrando a utilização do login
