### ISSUE TITLE
Estudo e implementação do Abstract User nas models do django

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#82]
## Descrição da Issue
- Como sugerido para request no pr #74 utilizar o abstract user como User do sistema de banco de dados

## Tasks:
- [x] Estudar as vantagens e desvantagens do uso do Abstract user
- [x] Implementação do Abstract user
- [x] Correção das models que utilizam a herança de User pelo Abstract User

## Critérios de Aceitação:
- [x] Estar claro para os integrantes as vantages/desvantagens do seu uso
- [x] Estar implementado no banco
- [x] Prints mostrando o banco em funcionamento com o Abstract User
