### ISSUE TITLE
Desenvolvimento do Frontend da User Story de Cadastro de Usuário

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#83]
## Descrição da Issue
- Por ser a primeira us, ela não possuia em sua issue (#61) o desenvolvimento do frontend baseado no documento de identidade visual (#77) sendo prorrogada para essa nova issue.

## Tasks:
- [x] Estudo sobre o documento visual
- [x] Implementação do novo visual
- [x] Possível melhoria do código do frontend

## Critérios de Aceitação:
- [x] Estar de acordo com a identidade visual do projeto
- [ ] Possuir prints de como ficou o frontend
