### ISSUE TITLE
[US02] - Apagar Conta

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#89]
## Descrição da Issue
- Eu, como usuário, gostaria de apagar minha conta

## Tasks:
- [x] Adicionar tela ao protótipo
- [x] Criar interface no frontend
- [x] Criar rotas no backend

## Critérios de Aceitação:
- [x] Manter % de coverage dos testes
- [x] Testes no backend
- [x] Testes no frontend
- [x] Interface utilizável no frontend
- [x] Backend seguindo padrão do projeto
