### ISSUE TITLE
[US04] - Sair da Conta

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#90]
## Descrição da Issue
- Eu, como usuário, gostaria de sair da minha conta

## Tasks:
- [x] Deslogar usuário ao clicar na opção "Sair"

## Critérios de Aceitação:
- [x] Usuário conseguir sair da conta
- [x] Ao efetuar a ação retornar para a tela de login
