### ISSUE TITLE
[US05] - Redefinir Senha

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#91]
## Descrição da Issue
- Eu, como usuário, gostaria de receber um email para recuperar a senha

## Tasks:
- [x] Utilizar sistema automatizado para enviar e-mail ao usuário
- [x] Ter interface no frontend

## Critérios de Aceitação:
- [x] Interface seguir o protótipo
- [x] Usuário receber a senha por email
- [x] Ter testado a funcionalidade
