### ISSUE TITLE
[US06] - Atualizar Dados de Usuário

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#92]
## Descrição da Issue
- Eu, como usuário, gostaria de atualizar meus dados

## Tasks:
- [x] Ter interface do frontend
- [x] Implementar atualização de dados no banco

## Critérios de Aceitação:
- [x] Interface seguir o protótipo
- [x] Dados serem atualizados no banco
- [x] Realizado testes unitários
