### ISSUE TITLE
[US07] - Registrar Produto

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#93]
## Descrição da Issue
- Eu, como produtor, gostaria de registrar um produto

## Tasks:
- [x] Criar interface no frontend
- [x] Desenvolver backend relativo aos produtos

## Critérios de Aceitação:
- [x] Interface seguir o protótipo
- [x] Ser possível registrar um produto 
- [x] Ficar salvo no banco
- [x] Ter testado a funcionalidade
