### ISSUE TITLE
[US08] - Editar Anúncio

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#94]
## Descrição da Issue
- Eu, como produtor, gostaria de editar um anúncio

## Tasks:
- [x] Criar tela no frontend
- [x] Adaptar o protótipo
- [x] Aplicar mudanças ao backend

## Critérios de Aceitação:
- [x] Interface seguir o protótipo
- [x] Conseguir editar anúncio
- [x] Conseguir deixar anúncio oculto
- [x] Testes Unitários
- [x] Testes de Integração
