### ISSUE TITLE
[US09] - Excluir Anúncio

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#95]
## Descrição da Issue
- Eu, como produtor, gostaria de excluir um anúncio

## Tasks:
- [x] Aplicar mudanças ao backend
- [x] Adicionar funcionalidade ao botão já implementado

## Critérios de Aceitação:
- [x] Conseguir excluir anúncio
- [x] Testes Unitários
- [x] Testes de Integração
