### ISSUE TITLE
[US10] - Pesquisar Produtor

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#96]
## Descrição da Issue
- Eu, como comprador, gostaria de pesquisar um produtor

## Tasks:
- [x] Adaptar interface no frontend
- [x] Criar rota de pesquisa no backend
- [x] Ligar a pesquisa no front com o back

## Critérios de Aceitação:
- [x] Ser possível visualizar anúncios pelo nome do produtor 
- [x] Feito testes

**Comment by VitorLamego** [comment]
Devido a necessidade de procurar pelos produtores e até o momento em que esta issue foi colocada no Sprint Backlog não tínhamos nenhuma interface que fazia essa função, então por conta disso foi refatorada a tela principal do Customer assim como a forma que o filtro da página estava funcionando.

Anteriormente o filtro era feito com os dados já presentes nas variáveis do mobile, com essa alteração o filtro passou a ser por meio de requisições ao servidor, tanto do produtor como do produto. Agora o Customer pode escolher se ele quer ver os anúncios ou se quer ver os produtores.

**Comment by Joao-Moura** [comment]
Em relação ao backend, a rota de `announcement/list` foi alterada de forma a permitir tanto querys de todos os anúncios **disponíveis**, quanto de apenas o nome pesquisado. A query funciona apenas com parte do nome (contains) e ja vem ordenada para facilitar o frontend. 

Outro ponto muito importande que foi implementado nessa issue foi a restrição de um produtor registrar vários anúncios com o mesmo nome, porém ainda permitindo no banco existir produtos com o mesmo nome. Além de é claro tornar o código mais enxuto possível para o backend.

**Comment by VitorLamego** [comment]
Em relação a algumas implementações na parte do Mobile. Esta issue começou a transição da utilização do pacote 'http' para o pacote 'Dio', a fim de realizar as requisições ao servidor. Por conta disso, foi necessário atualizar e alterar o formato de algumas variáveis, de rota, para se adequar ao formato necessário nas versões mais atualizadas.

Além disso iniciou-se a utilização do 'mockito' para realizar os testes que envolvem métodos que se relacionam com serviços externos. Com o 'mockito' podemos criar uma requisição falsa e retornar aquilo que era esperado, assim os testes não ficam lento nem são prejudicados por falhas ou alterações que os servidores podem sofrer.
