### ISSUE TITLE
[US11] - Procurar Produto

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#97]
## Descrição da Issue
- Eu, como comprador, gostaria de procurar por um produto

## Tasks:
- [x] Adaptar interface no frontend
- [x] Criar rotas no backend

## Critérios de Aceitação:
- [x] Ser possível visualizar anúncios pelo nome do anúncio 
- [x] Feito testes

**Comment by Joao-Moura** [comment]
Em relação ao backend, a rota de `announcement/list` foi alterada de forma a permitir tanto querys de todos os anúncios **disponíveis**, quanto de apenas o nome pesquisado. A query funciona apenas com parte do nome (contains) e ja vem ordenada para facilitar o frontend. 

Outro ponto muito importande que foi implementado nessa issue foi a restrição de um produtor registrar vários anúncios com o mesmo nome, porém ainda permitindo no banco existir produtos com o mesmo nome. Além de é claro tornar o código mais enxuto possível para o backend.
