### ISSUE TITLE
[US12] - Visualizar Anúncios de um Produtor

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#98]
## Descrição da Issue
- Eu, como comprador, gostaria de visualizar todos os produtos de um produtor

## Tasks:
- [x] Criar tela "Detalhes produtor"
- [x] Criar rotas no backend
- [x] Puxar dados do backend para mostrar informações do produtor

## Critérios de Aceitação:
- [x] Possibilidade de visualizar perfil do produtor com dados reais
- [x] Feito testes no backend
- [x] Feito testes no frontend
