### ISSUE TITLE
[US13] - Visualizar Localizações de um Anúncio

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#99]
## Descrição da Issue
- Eu, como comprador, gostaria de visualizar todas as localizações de um anúncio.

## Tasks:
- [x] Criar rotas no backend
- [x] Puxar dados do backend para mostrar informações no anúncio

## Critérios de Aceitação:
- [x] Possibilidade de visualizar localizações nos detalhes do anúncio
- [x] Feito testes no backend
- [x] Feito testes no frontend
